// <META - FILE SUMMARY - Korean UI strings central catalog (G1)>
export const STRINGS = Object.freeze({
  appTitle: "Draw Tool v2",
  menus: Object.freeze({
    file: "파일",
    edit: "편집",
    view: "보기",
    layer: "레이어",
  }),
  actions: Object.freeze({
    "file.new": "새로 만들기",
    "file.open": "열기",
    "file.save": "저장",
    "file.exportLayer": "레이어 내보내기",
    "file.importLayer": "레이어 가져오기",
    "file.exportPng": "PNG 내보내기",
    "file.importRecipe": "레시피 가져오기",
    "file.exportVector": "벡터 내보내기",
    "file.importVector": "벡터 가져오기",
    "edit.undo": "실행 취소",
    "edit.redo": "다시 실행",
    "canvas.resize": "캔버스 크기",
    "view.zoomIn": "확대",
    "view.zoomOut": "축소",
    "view.fit": "화면에 맞춤",
    "view.actual": "100%",
    "view.gridCycle": "그리드 순환",
    "layer.add": "추가",
    "layer.duplicate": "복제",
    "layer.remove": "삭제",
    "layer.mergeDown": "아래로 병합",
    "layer.up": "위로",
    "layer.down": "아래로",
  }),
  tools: Object.freeze({
    pen: "펜",
    eraser: "지우개",
    fill: "페인트통",
    eyedropper: "스포이트",
    line: "직선",
    rect: "사각형",
    rrect: "둥근 사각형",
    ellipse: "타원",
    polygon: "다각형",
    hand: "손",
  }),
  toolShortcuts: Object.freeze({
    pen: "B",
    eraser: "E",
    fill: "G",
    eyedropper: "I",
    line: "L",
    rect: "R",
    rrect: "U",
    ellipse: "O",
    polygon: "P",
    hand: "H",
  }),
  // Layer blend modes, keyed by BLEND_MODES (core/blend.js). The panel builds its
  // select from these keys, so a new mode needs one entry here and nowhere else.
  blends: Object.freeze({
    normal: "보통",
    multiply: "곱하기",
    screen: "스크린",
    overlay: "오버레이",
    darken: "어둡게",
    lighten: "밝게",
  }),
  hints: Object.freeze({
    penEraser: "Shift+클릭 = 직선, Alt+클릭 = 스포이트(펜)",
    fill: "클릭한 영역을 주색으로 채웁니다 (4방향, 허용오차 0)",
    eyedropper: "클릭 = 주색, Shift+클릭 = 보조색, Alt = 활성 레이어 기준",
    hand: "드래그로 화면 이동, 휠로 확대/축소",
    shape: "드래그로 그린 뒤 Enter 확정, Esc 취소",
    polygon: "클릭으로 정점 추가, 첫 정점 클릭·Enter 확정, Esc 한 점 되돌리기",
  }),
  color: Object.freeze({
    panel: "색상",
    primary: "주색",
    secondary: "보조색",
    swap: "주/보조 교체 (X)",
    reset: "기본색 (D)",
    hex: "HEX",
    palette: "팔레트",
    recent: "최근 색",
  }),
  brush: Object.freeze({
    panel: "브러시",
    size: "굵기",
  }),
  layers: Object.freeze({
    panel: "레이어",
    opacity: "불투명도",
    show: "표시",
    hide: "숨기기",
    lock: "잠금",
    unlock: "잠금 해제",
    rename: "이름 바꾸기 (더블클릭)",
  }),
  status: Object.freeze({
    dirty: "●",
  }),
  dialogs: Object.freeze({
    newDoc: "새 문서",
    create: "만들기",
    cancel: "취소",
    confirm: "확인",
    discard: "버리기",
    restore: "복원",
    widthTile: "너비(타일)",
    heightTile: "높이(타일)",
    background: "배경",
    transparent: "투명",
    colorBg: "색상",
    docName: "문서 이름",
    resizeCanvas: "캔버스 크기",
    restoreTitle: "자동저장 복원",
    discardTitle: "변경 버리기",
    preset1slot: "1슬롯 128×128",
    preset16slot: "16슬롯 512×512",
    preset64slot: "64슬롯 1024×1024",
    presetFhd: "풀HD 1920×1088",
  }),
  toast: Object.freeze({
    saved: "저장했습니다",
    opened: "문서를 열었습니다",
    exportedPng: "PNG를 내보냈습니다",
    exportedLayer: "레이어를 내보냈습니다",
    importedLayer: "레이어를 가져왔습니다",
    droppedChunks: "캔버스 밖 청크",
    layerFileHint: "레이어 파일입니다. 레이어 가져오기로 여십시오",
    unexpected: "예상치 못한 오류가 발생했습니다",
    importedRecipe: "레시피를 가져왔습니다",
    exportedVector: "벡터를 내보냈습니다",
    importedVector: "벡터를 가져왔습니다",
  }),
});

export function msg(key, fallback) {
  const v = STRINGS[key];
  return v === undefined ? fallback : v;
}
